version = 1

[[transformers]]
name = "black"
enabled = true

[[transformers]]
name = "isort"
enabled = true

[[analyzers]]
name = "python"
enabled = true
dependency_file_paths = ["requirements.txt", "requirements-dev.txt"]

[analyzers.meta]
runtime_version = "3.x.x"
max_line_length = 120
type_checker = "mypy"
