version: '3.4'

services:
  mybot:
    build:
      target: debug
    restart: "no"
    ports:
      - 5678:5678  # for debugging
      - 8080:8080

  database:
    expose:
      - 5432
