version: '3.4'

services:
  mybot:
    build:
      target: debug
    restart: "no"
    volumes:
      - ./src:/app/src
    ports:
      - 5678:5678
    expose:
      - 8080

  database:
    expose:
      - 5432
