version: '3'

services:
  mybot:
    build:
      context: .
      dockerfile: ./Dockerfile
      target: prod
    env_file:
      - .env
    tty: true
    restart: always
    depends_on:
      database:
        condition: service_healthy
    volumes:
      - ./data/locale:/app/locale
      - ./alembic:/app/alembic
    ports:
      - 8080:8080

  database:
    image: postgres:14.4-alpine
    env_file:
      - .env
    restart: always
    volumes:
      - ./data/database:/var/lib/postgresql/data
    ports:
      - "54321:5432"
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"
        ]
      interval: 5s
      timeout: 5s
      retries: 5
