version: '3'

services:
  mybot:
    build:
      context: .
      dockerfile: ./Dockerfile
      target: prod
    env_file:
      - .env
    tty: true
    restart: always
    depends_on:
      - "database"
    volumes:
      - ./data/locale:/app/locale
    ports:
      - 8080:8080

  database:
    image: postgres:14.4-alpine
    env_file:
      - .env
    restart: always
    volumes:
      - ./data/database:/var/lib/postgresql/data
    expose:
      - 5432
    ports:
      - "54321:5432"
