version: '3'

services:
  mybot:
    build:
      context: .
    env_file:
      - .env
    tty: true
    command:
      [
        "./wait-for-it.sh",
        "database:5432",
        "--",
        "python",
        "main.py"
      ]
    # restart: always
    depends_on:
      - "database"
  database:
    image: postgres:14.4-alpine
    env_file:
      - .env
    restart: always
    volumes:
      - ./data/database:/var/lib/postgresql/data
    ports:
      - "5432:5432"
