version: '3.4'

services:
  mybot:
    build:
      context: .
      dockerfile: ./Dockerfile
      target: debug
    env_file:
      - .env
    tty: true
    depends_on:
      - "database"
    ports:
      - 5678:5678
