[tool.bandit.assert_used]
skips = ["*/test_*.py", "*/test_*.py"]

[tool.pytest.ini_options]
pythonpath = ". src"

[tool.black]
line-length = 120

[tool.isort]
profile = "black"
combine_as_imports = true
combine_star = true
line_length = 120

[tool.pyright]
reportImportCycles = false
