# type: ignore

"""Update scheme

Revision ID: 075fbc7011f0
Revises: b94894dcf45a
Create Date: 2023-12-17 05:17:20.777664

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '075fbc7011f0'
down_revision = 'b94894dcf45a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ts_command_usage', sa.Column('guild_id', sa.BIGINT(), nullable=True))
    op.drop_constraint('ts_command_usage_guild_fkey', 'ts_command_usage', type_='foreignkey')
    op.create_foreign_key(None, 'ts_command_usage', 'guild', ['guild_id'], ['guild_id'])
    op.drop_column('ts_command_usage', 'guild')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ts_command_usage', sa.Column('guild', sa.BIGINT(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'ts_command_usage', type_='foreignkey')
    op.create_foreign_key('ts_command_usage_guild_fkey', 'ts_command_usage', 'guild', ['guild'], ['guild_id'])
    op.drop_column('ts_command_usage', 'guild_id')
    # ### end Alembic commands ###
