# type: ignore

"""Add default values, set nullables, add description prop to poll, and remove multiple.

Revision ID: 58cdd52a99e0
Revises: 58181eafb0cd
Create Date: 2023-02-21 19:42:33.561748

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58cdd52a99e0'
down_revision = '58181eafb0cd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('poll', sa.Column('title', sa.String(), nullable=False))
    op.add_column('poll', sa.Column('description', sa.String(), nullable=True))
    op.drop_column('poll', 'multiple')
    op.drop_column('poll', 'label')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('poll', sa.Column('label', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('poll', sa.Column('multiple', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('poll', 'description')
    op.drop_column('poll', 'title')
    # ### end Alembic commands ###
