# type: ignore

"""Add username and avatr to the user_db table

Revision ID: 82e8adf72f35
Revises: 075fbc7011f0
Create Date: 2024-09-01 15:58:50.925063

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82e8adf72f35'
down_revision = '075fbc7011f0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('username', sa.String(), nullable=False))
    op.add_column('user', sa.Column('avatar', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'avatar')
    op.drop_column('user', 'username')
    # ### end Alembic commands ###
