# type: ignore

"""Add url to poll table

Revision ID: a0556697d480
Revises: 82e8adf72f35
Create Date: 2024-09-03 21:58:21.606304

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.orm import Session

try:
    import fastnanoid
except ImportError:
    fastnanoid = None

# revision identifiers, used by Alembic.
revision = 'a0556697d480'
down_revision = '82e8adf72f35'
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.add_column('poll', sa.Column('url', sa.VARCHAR(length=21), nullable=True))

    connection = op.get_bind()
    session = Session(bind=connection)

    if fastnanoid is None:
        return

    try:
        rows = session.execute(sa.select([sa.table('poll')])).fetchall()

        for row in rows:
            session.execute(
                sa.update(sa.table('poll'))
                .where(sa.text('id = :id'))
                .values(url=fastnanoid.generate()),
                {'id': row['id']}
            )

        session.commit()
    finally:
        session.close()

    op.alter_column('poll', 'url', nullable=False)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('poll', 'url')
    # ### end Alembic commands ###
