# type: ignore

"""Change Date to DateTime

Revision ID: b9b8f970b67f
Revises: 58cdd52a99e0
Create Date: 2023-02-24 00:17:10.159022

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "b9b8f970b67f"
down_revision = "58cdd52a99e0"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("poll", "creation_date", type_=sa.DateTime(timezone=True))
    op.alter_column("poll", "end_date", type_=sa.DateTime(timezone=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("poll", "creation_date", type_=sa.Date())
    op.alter_column("poll", "end_date", type_=sa.Date())
    # ### end Alembic commands ###
