name: Download from crowdin

on:
  workflow_dispatch:
  schedule:
    - cron: 0 * * * *

jobs:
  download:
    runs-on: ubuntu-latest
    # secrets cannot be accessed inside an `if` so this needs to be checked in separate job
    name: dowload
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: master

      - name: Install crowdin cli
        run: |
          wget -qO - https://artifacts.crowdin.com/repo/GPG-KEY-crowdin | sudo apt-key add -
          echo "deb https://artifacts.crowdin.com/repo/deb/ /" | sudo tee -a /etc/apt/sources.list.d/crowdin.list
          sudo apt-get update && sudo apt-get install crowdin3

      - name: Download translations
        shell: bash
        run: |
          crowdin download --all
        env:
          CROWDIN_API_KEY: ${{ secrets.CROWDIN_API_KEY }}

      # - uses: EndBug/add-and-commit@v9
      #   with:
      #     message: "PO files updated."

      # - name: Create pull request
      #   id: cpr_crowdin
      #   uses: peter-evans/create-pull-request@v3
      #   with:
      #     token: ${{ secrets.GITHUB_TOKEN }}
      #     commit-message: Crowdin translations download
      #     title: "[Crowdin] Updated translation files"
      #     body: |
      #       Created by the [Crowdin download workflow](.github/workflows/crowdin_download.yml).
      #     branch: "auto/crowdin"
      #     author: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>

      - name: create pull request
        run: gh pr create -B auto/crowdin -H master --title 'Update translations.' --body 'Created by Github action'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
