name: Publish Docker image

on:
  push:
    tags:
      - "*"

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Establish if it is a beta version
        run: |
          pat="refs/tags/v[0-9.]+b.+"
          if [[ ${{ github.ref }} =~ $pat ]]; then echo -e "beta=true\nstable=false" >> $GITHUB_ENV; else echo -e "beta=false\nstable=true" >> $GITHUB_ENV; fi

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: airopi/mybot
          tags: |
            type=raw,enable=${{ env.beta }},value=beta
            type=raw,enable=${{ env.stable }},value=stable
            type=pep440,pattern={{raw}}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          target: prod
