name: Generate pot file

on:
  push:
    branches: [feat/fix-pot-file-generation]
    paths:
      - "**.py"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_TOKEN }}
          ref: ${{ github.ref }}

      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: babel extract (pot file generation)
        run: |
          pip install babel
          ls
          sh ./bin/generate-pot-file.yml

      - uses: EndBug/add-and-commit@v9
        with:
          push: --force
          message: "POT file generated."
