name: Generate MO from PO files

on:
  push:
    branches: [auto/crowdin]
    paths:
      - "**.po"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_TOKEN }}

      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Run a one-line script
        run: sh ./bin/po-to-mo.sh

      - uses: EndBug/add-and-commit@v9
        with:
          message: "MO files generated."
