name: Generate pot file

on:
  workflow_dispatch:
  push:
    branches: [master]
    paths:
      - "**.py"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_TOKEN }}

      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          cache: pip

      - name: babel extract (pot file generation)
        run: |
          pip install babel
          sh ./bin/pot-generation.sh
          git checkout auto/translations-source

      - uses: EndBug/add-and-commit@v9
        with:
          new_branch: auto/translations-source
          message: "POT file generated."
