name: Generate po template file

on:
  push:
    branches: [feat/fix-pot-file-generation]
    paths:
      - "**.py"

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: airopi/gettext:0.21.1
      volumes:
        - ./:/tmp

    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_TOKEN }}
          ref: ${{ github.ref }}

      - name: Execute xgettext
        run: |
          cd tmp
          ls
          xgettext -d mybot -p ./data/locale -o mybot.pot -L python -k__ --from-code UTF-8 ./src/**/*.py

      - uses: EndBug/add-and-commit@v9
        with:
          push: --force
          message: "POT file generated."
