name: Generate pot file

on:
  workflow_dispatch:
  push:
    branches: [master]
    paths:
      - "**.py"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          ref: master
          path: master/

      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          cache: pip

      - name: babel extract (pot file generation)
        run: |
          cd master
          pip install babel
          sh ./bin/pot-generation.sh

      - name: setup git
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"

      - uses: actions/checkout@v3
        with:
          ref: auto/translations-source
          path: translations/

      - name: commit
        run: |
          ls
