name: Generate MO from PO files

on:
  push:
    branches: [ auto/crowdin ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10' 

      - name: Run a one-line script
        run: python ./bin/msgfmt.py ./data/locale/**/LC_MESSAGES/*.po
        
      - uses: EndBug/add-and-commit@v9
        with:
          message: 'MO files generated.'
          
