name: Generate po template file

on:
  pull_request:
    branches: [ dev ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      - name: install xgettext
        run: |
          sudo apt-get update
          sudo apt-get install gettext

      - name: Execute xgettext
        run: xgettext -d mybot -p ./data/locale -o mybot.pot -L python -k__ --from-code UTF-8 ./src/**/*.py

      - uses: EndBug/add-and-commit@v9
        with:
          message: 'POT file generated.'
